[package]

name = "capnp-rpc"
version = "0.7.4"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.7"

[dependencies]
futures = "0.1"
capnp-futures = "0.0.2"
capnp = {version = "0.7", features = ["rpc"]}

[replace]
"capnp:0.7.5" = { git = "https://github.com/dwrensha/capnproto-rust", branch = "futures" }
"capnpc:0.7.5" = { git = "https://github.com/dwrensha/capnpc-rust", branch = "futures" }
"capnp-futures:0.0.2" = { git = "https://github.com/dwrensha/capnp-futures-rs" }