[package]

name = "capnp-rpc"
version = "0.8.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.8"

[dependencies]
futures = "0.1"
capnp-futures = "0.1"
capnp = {version = "0.8", features = ["rpc"]}
