[package]

name = "capnp"
version = "0.1.19"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "Runtime library for Cap'n Proto serialization"
repository = "https://github.com/dwrensha/capnproto-rust"

readme = "README.md"

keywords = ["protocol", "serialization"]

[lib]

name = "capnp"
path = "src/lib.rs"

