[package]

name = "capnp"
version = "0.0.1"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "Runtime library for Cap'n Proto serialization"

[lib]

name = "capnp"
path = "src/capnp/lib.rs"
