[package]

name = "capnp"
version = "0.1.0"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]

[lib]

name = "capnp"
path = "capnp/lib.rs"

[[bin]]

name = "capnpc-rust"
path = "capnpc-rust/main.rs"